### PR TITLE
fix(schemas): update parse migrations and schemas types

### LINKED ISSUE #15: CLPHelper is undefined
Hi! Thanks for this repo! I was just setting it up and noticed the `CLPHelper` on the `SchemaMigrations` does not exist and leads to an undefined error from `ts-node`. Any ideas what this could be about? For now, I removed the below line and use object definitions for the CLP to get it working. But would love to learn more about this CLPHelper, if it still exists in parse-server.

```
$ TS_NODE_FILES=true node --require ts-node/register --trace-warnings ./src/index.ts
/home/deniz/dev/examples/parse-server-typescript/src/schema/User.schema.ts:32
        ...SchemaMigrations.CLPHelper.requiresAuthentication(["find", "count", "get"]),
                                      ^
TypeError: Cannot read properties of undefined (reading 'requiresAuthentication')
    at Object.<anonymous> (/home/deniz/dev/examples/parse-server-typescript/src/schema/User.schema.ts:32:39)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Module.m._compile (/home/deniz/dev/examples/parse-server-typescript/node_modules/ts-node/src/index.ts:1455:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (/home/deniz/dev/examples/parse-server-typescript/node_modules/ts-node/src/index.ts:1458:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/deniz/dev/examples/parse-server-typescript/src/schema/index.ts:2:1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### PR DESCRIPTION
**Pull request by azlekov**

### CODE REVIEW

**Comment by isokosan** [comment]
Thanks for this, no longer getting the error. I want to add another quick note, currently I'm not sure what the `migrations` key in the `ParseServerOptions` is doing, when I change that to below, the migrations are auto-applied as expected. Maybe you want to have a look before merging? 

`parse-server.ts`
```
    schema: {
        strict: true,
        definitions: schemas,
    },
```

instead of the current:
```
    migrations: {
        strict: true,
        schemas: schemas,
    },
```

**Comment by azlekov** [comment]
A-haa, thanks @isokosan. I had here configured the defined schemas before they was release, so that's why differs. I will double check parse server configuration options.

**Comment by azlekov** [comment]
Done @isokosan, any other findings, fixes or improvements to be added here? What do you think? 💭

**Comment by isokosan** [comment]
Alright, amazing! Yes one more thing: the default Parse fields do not need to be listed in the schema fields. Have a look [here](https://github.com/GoPlan-Finance/goplan-app/tree/master/backend/src/Migrations/schemas) to see some examples.
 
I also tested this branch with a new class schema just to make sure, and upon adding a single field the 4 default fields are defined automatically.
 
By the way in the repo link I sent, the author used a CLP class helper like the one you had before, but I think the regular style is good as is. If you like the way this author did it feel free to add something like that!
 
Once you merge the pull request, I'll re-fork and add the nodemon and module-aliases :)

**Comment by azlekov** [comment]
@isokosan whenever you have time, to check again?

**Comment by isokosan** [comment]
Hmm I couldn't get the Migrations namespace to work, when I rename it to SchemaMigrations, it works as expected. This is probably due to ParseServer internally using SchemaMigrations. Not sure if that's the reason but in the future, they will release the types under this naming so better to go with `SchemaMigrations` I guess. 

I also needed to add a ts-ignore in the `schema/index.ts` file here:
```
import { SchemaMigrations } from 'parse-server'
import UserSchema from "./User.schema";

// @ts-ignore
export const schemas: SchemaMigrations.JSONSchema[] = [UserSchema];
```

**Comment by azlekov** [comment]
@isokosan I was looking the structure here for example: https://github.com/parse-community/parse-server/blob/alpha/src/SchemaMigrations/Migrations.js

**Comment by azlekov** [comment]
@isokosan sorry for the ping-pong if you can quickly check again and hopefully merge this...

**Comment by isokosan** [comment]
Thanks @L3K0V  but I can't get this config to work, and run into the following error right off the bat. Can you confirm you're getting the same error, if so I will make a working example and submit changes here. 

```
/home/deniz/dev/examples/parse-server-typescript/src/schema/User.schema.ts:3
export default SchemaMigrations.makeSchema("_User", {
                                ^
TypeError: Cannot read properties of undefined (reading 'makeSchema')
```

**Comment by azlekov** [comment]
@isokosan unfortunately I cannot get the both of two words working, so `@ts-ignore` is required 😢 

And something else - I did try to run the parse server but without any success:

```
yarn start
yarn run v1.22.18
$ node dist/src/index.js
warn: DeprecationWarning: The Parse Server option 'directAccess' default will change to 'true' in a future version. Additionally, the environment variable 'PARSE_SERVER_ENABLE_EXPERIMENTAL_DIRECT_ACCESS' will be deprecated and renamed to 'PARSE_SERVER_DIRECT_ACCESS' in a future version; it is currently possible to use either one.
warn: DeprecationWarning: The Parse Server option 'enforcePrivateUsers' default will change to 'true' in a future version.
✨  Done in 4.43s.
```

Did you face such issue starting the server actually finish quite unexpectedly without any traces?

**Review by isokosan — APPROVED** [review]
Yeah I also couldn't figure out a way around the `// @ts-ignore` 

The start command is also now working for me with the `src/` addition, before was not working.

**Comment by azlekov** [comment]
Does the server start properly? I cannot get it running

**Comment by isokosan** [comment]
Yes, `node dist/src/index.js` is starting the server as expected

**Pull request merged**
